import { Product } from "./types";

export const categories = [
    {
        id: "sarees",
        name: "Sarees",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX_c0wIqK86x8-kHxe0YflK_VlbtZa4xHIhg&s",
        slug: "sarees",
    },
    {
        id: "kurtis",
        name: "Kurtis",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJhgg85rktLLM0HuL5LrkObqIDKUT42918FA&s",
        slug: "kurtis",
    },
    {
        id: "lehengas",
        name: "Lehengas",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjY2K5RL0zNPQpxVQG5MFCS6pFLFB8OQ24sA&s",
        slug: "lehengas",
    },
    {
        id: "dresses",
        name: "Dresses",
        image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop",
        slug: "dresses",
    },
    {
        id: "coords",
        name: "Co-ords",
        image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800&auto=format&fit=crop",
        slug: "coords",
    },
];

export const products: Product[] = [
    {
        id: "1",
        name: "Royal Banarasi Silk Saree",
        description: "Handwoven Banarasi silk saree in deep maroon with intricate gold zari work. Perfect for weddings and festive occasions.",
        price: 12999,
        originalPrice: 18999,
        discount: 32,
        images: [
            "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1583391733956-3750e186e28b?q=80&w=800&auto=format&fit=crop",
        ],
        category: "Sarees",
        sizes: ["Free Size"],
        colors: ["Maroon", "Gold"],
        fabric: "Banarasi Silk",
        isTrending: true,
        rating: 4.8,
        reviews: 124,
        inStock: true,
    },
    {
        id: "2",
        name: "Floral Georgette Anarkali",
        description: "Lightweight georgette Anarkali suit with hand-painted floral motifs and a matching dupatta.",
        price: 4599,
        originalPrice: 5999,
        discount: 23,
        images: [
            "https://images.unsplash.com/photo-1596783074918-c84cb06c9ca8?q=80&w=800&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1583391733956-3750e186e28b?q=80&w=800&auto=format&fit=crop",
        ],
        category: "Kurtis",
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Pink", "Peach"],
        fabric: "Georgette",
        isNew: true,
        rating: 4.5,
        reviews: 89,
        inStock: true,
    },
    {
        id: "3",
        name: "Bridal Red Lehenga",
        description: "Heavily embroidered velvet lehenga in bridal red, featuring antique gold thread work and sequins.",
        price: 45000,
        originalPrice: 65000,
        discount: 30,
        images: [
            "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop",
        ],
        category: "Lehengas",
        sizes: ["M", "L", "Custom"],
        colors: ["Red", "Gold"],
        fabric: "Velvet",
        rating: 5.0,
        reviews: 42,
        inStock: true,
    },
    {
        id: "4",
        name: "Chic Cotton Co-ord Set",
        description: "Modern block printed cotton co-ord set with blazer style top and straight pants.",
        price: 2499,
        images: [
            "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop",
        ],
        category: "Co-ords",
        sizes: ["XS", "S", "M", "L"],
        colors: ["Indigo", "White"],
        fabric: "Cotton",
        isTrending: true,
        rating: 4.6,
        reviews: 56,
        inStock: true,
    },
    {
        id: "5",
        name: "Festive Silk Kurti Set",
        description: "Elegant silk kurti with cigarette pants and organza dupatta. Minimalist embroidery on the neckline.",
        price: 3999,
        originalPrice: 4999,
        images: [
            "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800&auto=format&fit=crop",
        ],
        category: "Kurtis",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Mustard", "Gold"],
        fabric: "Chanderi Silk",
        rating: 4.7,
        reviews: 34,
        inStock: true,
    },
    {
        id: "6",
        name: "Kanjivaram Silk Saree",
        description: "Traditional Kanjivaram silk saree in emerald green with contrasting pink border.",
        price: 15999,
        originalPrice: 22000,
        discount: 27,
        images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop"],
        category: "Sarees",
        sizes: ["Free Size"],
        colors: ["Green", "Pink"],
        fabric: "Kanjivaram Silk",
        isNew: true,
        rating: 4.9,
        reviews: 15,
        inStock: true,
    },
];
